### ISSUE TITLE
AttributeError exception while trying to run simple code

### ISSUE THREAD

**Issue by vladimarius** [mortencombat/stretchable#98]
I am tinkering with this package and trying to run following code:
```
from stretchable import Node

# Create the parent flex container
flex_container = Node(
    style={
        "width": 1000,
        "height": 200,
        "alignItems": "CENTER",
        "justifyContent": "CENTER",
        "flexDirection": "ROW",
    }
)

# Create the first child
first_child = Node(style={"width": 50, "height": 50})
flex_container.append_child(first_child)

# Create the second child with flex-grow: 1
second_child = Node(style={"flexGrow": 1})
flex_container.append_child(second_child)

# Create the third child
third_child = Node(style={"width": 30, "height": 30})
flex_container.append_child(third_child)

# Perform the layout calculation
flex_container.layout(width=1000, height=200)
```

It all fails with following exception:
```
Traceback (most recent call last):
  File "/tmp/test.py", line 4, in <module>
    flex_container = Node(
                     ^^^^^
  File "/tmp/env/lib/python3.12/site-packages/stretchable/node.py", line 194, in __init__
    self.__ptr = taffylib.node_create(taffy._ptr, style._ptr)
                                                  ^^^^^^^^^^
AttributeError: 'dict' object has no attribute '_ptr'
```

(I am using Python 3.12.3 under MacOS Sonoma)

What is wrong with my code and how do I fix it ?

**Comment by vladimarius** [comment]
Thank you, @mortencombat !
